language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer install --dev

script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml
 # - vendor/bin/phpdoc --template="checkstyle" -d src/ -t docs/ --cache-folder docs/cache/ && if [[ `cat "docs/checkstyle.xml" | grep "<error "` != "" ]]; then exit 1; fi
