language: php

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml
  - vendor/bin/phpdoc --template="checkstyle" -d src/ -t docs/ --cache-folder docs/cache/ && if [[ `cat "docs/checkstyle.xml" | grep -v "No summary was found for this file" | grep "<error "` != "" ]]; then exit 1; fi

matrix:
  fast_finish: true
  include:
    - name: "PHP 7.1 No ENV"
      php: 7.1
    - name: "PHP 7.2 No ENV"
      php: 7.2
    - name: "PHP 7.3 No ENV"
      php: 7.3

    - name: "PHP 7.1 Invalid ENV"
      php: 7.1
      env: APIKEY="FAKE"
    - name: "PHP 7.2 Invalid ENV"
      php: 7.2
      env: APIKEY="FAKE"
    - name: "PHP 7.3 Invalid ENV"
      php: 7.3
      env: APIKEY="FAKE"

    - name: "PHP 7.1 With Valid ENV"
      php: 7.1
      env:
        - secure: "O4F1+EoGMo1g6IPZhPZcqP0MnkpW13lly4SpZ2+k/bViHSlEIxxwzew1nvgq6z7KthjIpcVJPhM2Ny1PR32LtDaHogpzH9lmN67/sGyy9aXs+cO4rPx+oRbdd1U4o8tKKOTmP4HAttvDHJuPrnQcf5IXhl+YXLzy8Btwy381FsoOk0rNt3n719gU+byNTRbpRUCAlVfItQC654la9z/MTxoCN3TbWlNDDMZyaJqJV6P5lpmBcFy0Jmj5qBlew/V1avg3GcPAnUpgkF0JjIMGEpxor6FjEW3X1rcU0C9ENfoqKf3KXaVQdZAu80SNoiYoLB1vvsi83Dhw1QELU46J3/ibnmuQBpNHE3+kvZbUePGpwbnUsesLep+Mve2bJ43tlVY2VEa8MlBqOE2YfNZW+nqeUuFKNBU07QyWSNcjxsZnce2R0HXPg/crT/rqiOzp+y+Jqb31X9psnjWT1wY6pksI8pQOz+NduvLlNVabP/wPrPUKa8TpkKNtINdVmeuFdzF1vFysYU5bhU/PvFcBZXG/76iPGvxPDPBA1cq3TaKxac8e3QAqK7chmaiBgW3UhxffERfXiC+0gE6vcQ8ZLTyq69CGNybOTrDDxeswlHPvO4/Iw10M6xSOUECkPM+ZusGk0cg/q5XybhwaVeMf4iUvGHo5g5lI0u2GV0aZpoo="
    - name: "PHP 7.2 With Valid ENV"
      php: 7.2
      env:
        - secure: "O4F1+EoGMo1g6IPZhPZcqP0MnkpW13lly4SpZ2+k/bViHSlEIxxwzew1nvgq6z7KthjIpcVJPhM2Ny1PR32LtDaHogpzH9lmN67/sGyy9aXs+cO4rPx+oRbdd1U4o8tKKOTmP4HAttvDHJuPrnQcf5IXhl+YXLzy8Btwy381FsoOk0rNt3n719gU+byNTRbpRUCAlVfItQC654la9z/MTxoCN3TbWlNDDMZyaJqJV6P5lpmBcFy0Jmj5qBlew/V1avg3GcPAnUpgkF0JjIMGEpxor6FjEW3X1rcU0C9ENfoqKf3KXaVQdZAu80SNoiYoLB1vvsi83Dhw1QELU46J3/ibnmuQBpNHE3+kvZbUePGpwbnUsesLep+Mve2bJ43tlVY2VEa8MlBqOE2YfNZW+nqeUuFKNBU07QyWSNcjxsZnce2R0HXPg/crT/rqiOzp+y+Jqb31X9psnjWT1wY6pksI8pQOz+NduvLlNVabP/wPrPUKa8TpkKNtINdVmeuFdzF1vFysYU5bhU/PvFcBZXG/76iPGvxPDPBA1cq3TaKxac8e3QAqK7chmaiBgW3UhxffERfXiC+0gE6vcQ8ZLTyq69CGNybOTrDDxeswlHPvO4/Iw10M6xSOUECkPM+ZusGk0cg/q5XybhwaVeMf4iUvGHo5g5lI0u2GV0aZpoo="
    - name: "PHP 7.3 With Valid ENV"
      php: 7.3
      env:
        - secure: "O4F1+EoGMo1g6IPZhPZcqP0MnkpW13lly4SpZ2+k/bViHSlEIxxwzew1nvgq6z7KthjIpcVJPhM2Ny1PR32LtDaHogpzH9lmN67/sGyy9aXs+cO4rPx+oRbdd1U4o8tKKOTmP4HAttvDHJuPrnQcf5IXhl+YXLzy8Btwy381FsoOk0rNt3n719gU+byNTRbpRUCAlVfItQC654la9z/MTxoCN3TbWlNDDMZyaJqJV6P5lpmBcFy0Jmj5qBlew/V1avg3GcPAnUpgkF0JjIMGEpxor6FjEW3X1rcU0C9ENfoqKf3KXaVQdZAu80SNoiYoLB1vvsi83Dhw1QELU46J3/ibnmuQBpNHE3+kvZbUePGpwbnUsesLep+Mve2bJ43tlVY2VEa8MlBqOE2YfNZW+nqeUuFKNBU07QyWSNcjxsZnce2R0HXPg/crT/rqiOzp+y+Jqb31X9psnjWT1wY6pksI8pQOz+NduvLlNVabP/wPrPUKa8TpkKNtINdVmeuFdzF1vFysYU5bhU/PvFcBZXG/76iPGvxPDPBA1cq3TaKxac8e3QAqK7chmaiBgW3UhxffERfXiC+0gE6vcQ8ZLTyq69CGNybOTrDDxeswlHPvO4/Iw10M6xSOUECkPM+ZusGk0cg/q5XybhwaVeMf4iUvGHo5g5lI0u2GV0aZpoo="

after_success:
  - travis_retry php vendor/bin/php-coveralls